import { useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { ArrowLeft, ArrowRight, Check, CircleDot, Plus, Save, Sparkles, Trash2 } from "lucide-react";
import { saveEnvironment, type EnvironmentTask } from "../api/client";

const steps = ["Purpose", "Interaction", "Reward", "Tasks"];
const emptyTask = (): EnvironmentTask => ({ name: "", prompt: "", expected_answer: "", criteria: [], difficulty: "medium" });

export default function EnvironmentBuilderPage() {
  const [step, setStep] = useState(0);
  const [mode, setMode] = useState<"IL"|"RL">("IL");
  const [name, setName] = useState("");
  const [goal, setGoal] = useState("");
  const [description, setDescription] = useState("");
  const [domain, setDomain] = useState("reasoning");
  const [observation, setObservation] = useState("A natural-language task prompt");
  const [action, setAction] = useState("A reasoned response with a final answer");
  const [maxSteps, setMaxSteps] = useState(1);
  const [reward, setReward] = useState({correctness:60, reasoning:30, efficiency:10});
  const [tasks, setTasks] = useState<EnvironmentTask[]>([emptyTask()]);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");
  const navigate = useNavigate();
  const total = reward.correctness + reward.reasoning + reward.efficiency;
  const valid = useMemo(() => name.trim().length >= 3 && goal.trim().length >= 12 && tasks.every((task) => task.prompt.trim()), [name, goal, tasks]);

  const updateTask = (index:number, patch:Partial<EnvironmentTask>) => setTasks((current) => current.map((task, i) => i === index ? {...task,...patch} : task));
  const save = async () => { setSaving(true); setError(""); try { const environment = await saveEnvironment({name,mode,goal,description:description||goal,domain,interaction:{observation,action,max_steps:maxSteps},reward:{correctness:reward.correctness,reasoning:reward.reasoning,efficiency:reward.efficiency,method:"criteria"},tasks} as any); navigate(`/environments?created=${environment.id}`); } catch (err) { setError(err instanceof Error ? err.message : "Could not save environment"); } finally { setSaving(false); } };

  return <section className="product-page builder-product">
    <header className="builder-header"><div><span className="product-kicker"><Sparkles /> No-code environment designer</span><h1>Build a world for your model.</h1><p>Define the goal, interaction, reward, and tasks. Optimus turns it into a trainable taskset.</p></div><div className="mode-switch"><button className={mode==="IL"?"selected":""} onClick={()=>setMode("IL")}><strong>IL</strong><span>Teach the ideal behavior</span></button><button className={mode==="RL"?"selected":""} onClick={()=>setMode("RL")}><strong>RL</strong><span>Learn through reward</span></button></div></header>
    <div className="builder-shell">
      <aside className="step-rail">{steps.map((label,index)=><button key={label} className={`${index===step?"active":""} ${index<step?"done":""}`} onClick={()=>setStep(index)}><span>{index<step?<Check />:index+1}</span><div><strong>{label}</strong><small>{["What should it learn?","What does it see and do?","What counts as good?","What will it practice?"][index]}</small></div></button>)}</aside>
      <main className="builder-form">
        {step===0&&<div className="form-section"><span className="section-number">01 — Purpose</span><h2>What capability are you building?</h2><p>Plain language is enough. This becomes the source of truth for every task and reward.</p><label>Environment name<input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Careful contract reviewer" /></label><label>Learning goal<textarea value={goal} onChange={e=>setGoal(e.target.value)} placeholder="The model should identify risky clauses, explain why they matter, and propose safer language." /></label><div className="two-fields"><label>Domain<select value={domain} onChange={e=>setDomain(e.target.value)}><option>reasoning</option><option>coding</option><option>agentic</option><option>tool-use</option><option>knowledge</option></select></label><label>Short description<input value={description} onChange={e=>setDescription(e.target.value)} placeholder="Optional public description" /></label></div></div>}
        {step===1&&<div className="form-section"><span className="section-number">02 — Interaction</span><h2>Design the learning loop.</h2><p>An environment is a repeated loop: observe, act, receive feedback, improve.</p><div className="loop-visual"><div><small>1</small><strong>Observation</strong><span>{observation}</span></div><ArrowRight/><div><small>2</small><strong>Model action</strong><span>{action}</span></div><ArrowRight/><div><small>3</small><strong>Reward</strong><span>Scored against your rules</span></div></div><label>What does the model receive?<input value={observation} onChange={e=>setObservation(e.target.value)} /></label><label>What must the model produce?<input value={action} onChange={e=>setAction(e.target.value)} /></label><label className="short-label">Maximum steps<input type="number" min="1" max="64" value={maxSteps} onChange={e=>setMaxSteps(Number(e.target.value))} /></label></div>}
        {step===2&&<div className="form-section"><span className="section-number">03 — Reward</span><h2>Tell the model what “better” means.</h2><p>The weights are normalized automatically. Correctness can gate the score while reasoning and efficiency shape behavior.</p>{Object.entries(reward).map(([key,value])=><label className="reward-slider" key={key}><span><strong>{key}</strong><em>{value}%</em></span><input type="range" min="0" max="100" value={value} onChange={e=>setReward({...reward,[key]:Number(e.target.value)})}/><small>{key==="correctness"?"Did it reach the right outcome?":key==="reasoning"?"Did it follow the desired process?":"Did it avoid wasted steps and tokens?"}</small></label>)}<div className="reward-equation"><CircleDot/><span>Final reward</span><strong>{total ? `${reward.correctness}/${total} correct + ${reward.reasoning}/${total} reasoning + ${reward.efficiency}/${total} efficient` : "Add at least one weight"}</strong></div></div>}
        {step===3&&<div className="form-section"><span className="section-number">04 — Tasks</span><h2>Create concrete practice situations.</h2><p>Each task becomes a real benchmark and training example. Expected answers are optional when criteria are enough.</p>{tasks.map((task,index)=><div className="task-editor" key={index}><div className="task-editor-head"><strong>Task {index+1}</strong>{tasks.length>1&&<button onClick={()=>setTasks(tasks.filter((_,i)=>i!==index))}><Trash2/> Remove</button>}</div><div className="two-fields"><label>Name<input value={task.name} onChange={e=>updateTask(index,{name:e.target.value})} placeholder="Baseline scenario"/></label><label>Difficulty<select value={task.difficulty} onChange={e=>updateTask(index,{difficulty:e.target.value})}><option>easy</option><option>medium</option><option>hard</option></select></label></div><label>Prompt<textarea value={task.prompt} onChange={e=>updateTask(index,{prompt:e.target.value})} placeholder="Describe exactly what the model must do in this situation."/></label><label>Expected answer<input value={task.expected_answer} onChange={e=>updateTask(index,{expected_answer:e.target.value})} placeholder="Optional exact or contained answer"/></label><label>Success criteria<input value={task.criteria.join(", ")} onChange={e=>updateTask(index,{criteria:e.target.value.split(",").map(v=>v.trim()).filter(Boolean)})} placeholder="clear explanation, identifies risk, verifies result"/></label></div>)}<button className="add-task" onClick={()=>setTasks([...tasks,emptyTask()])}><Plus/> Add another task</button></div>}
        {error&&<div className="form-error">{error}</div>}
        <footer className="builder-nav"><button disabled={step===0} onClick={()=>setStep(step-1)}><ArrowLeft/> Back</button>{step<3?<button className="continue" onClick={()=>setStep(step+1)}>Continue <ArrowRight/></button>:<button className="continue" disabled={!valid||saving} onClick={save}><Save/> {saving?"Building…":"Build environment"}</button>}</footer>
      </main>
      <aside className="builder-preview"><span className="preview-label">Live blueprint</span><div className="blueprint-card"><div className="blueprint-top"><span>{mode}</span><em>{domain}</em></div><h3>{name||"Untitled environment"}</h3><p>{goal||"Your learning goal will appear here."}</p><div className="blueprint-stats"><div><small>Tasks</small><strong>{tasks.length}</strong></div><div><small>Steps</small><strong>{maxSteps}</strong></div><div><small>Reward</small><strong>{total}%</strong></div></div></div><div className="validation-list"><strong>Ready check</strong><span className={name.length>=3?"ok":""}><Check/> Clear name</span><span className={goal.length>=12?"ok":""}><Check/> Defined goal</span><span className={tasks.every(t=>t.prompt)?"ok":""}><Check/> Gradable tasks</span><span className={total>0?"ok":""}><Check/> Reward signal</span></div></aside>
    </div>
  </section>;
}
